# Generated by Django 5.2.7 on 2025-11-01 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Скидка (₸/кг)')),
                ('is_temporary', models.BooleanField(default=False, verbose_name='Разовая скидка')),
                ('active', models.BooleanField(default=True, verbose_name='Активная скидка')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Статус оплаты')),
                ('total_weight', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Общий вес (кг)')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Сумма чека')),
                ('pickup_point', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пункт выдачи')),
                ('payment_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='TrackCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='№ трек кода')),
                ('track_code', models.CharField(max_length=100, unique=True, verbose_name='Трек код')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('user_added', 'Добавлено пользователем'), ('warehouse_cn', 'Принято на склад (Китай)'), ('shipped_cn', 'Отправлено со склада (Китай)'), ('delivered', 'Принято сортировочным центром'), ('ready', 'Доставлено на ПВЗ'), ('claimed', 'Выдано получателю')], max_length=20, verbose_name='Статус трек-кода')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='О посылке')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Вес посылки (кг)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя владельца')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myprofile.receipt')),
                ('track_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myprofile.trackcode')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraditionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Штрихкод выдачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_issued', models.BooleanField(default=False, verbose_name='Выдано клиенту')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extradition_packages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('track_codes', models.ManyToManyField(related_name='extradition_packages', to='myprofile.trackcode', verbose_name='Трек-коды')),
            ],
        ),
        migrations.CreateModel(
            name='Extradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_point', models.CharField(max_length=255, verbose_name='Пункт выдачи')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтверждено получателем')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_extraditions', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник, выдавший посылку')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraditions', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraditions', to='myprofile.receipt', verbose_name='Чек')),
                ('track_codes', models.ManyToManyField(related_name='extraditions', to='myprofile.trackcode', verbose_name='Трек-коды')),
            ],
            options={
                'verbose_name': 'Выдача посылки',
                'verbose_name_plural': 'Выдачи посылок',
            },
        ),
        migrations.CreateModel(
            name='UserPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_data', models.JSONField(blank=True, default=dict, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
