# Generated by Django 5.2.7 on 2025-10-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraditionpackage',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Штрихкод выдачи'),
        ),
    ]
